name: Driver DUA

on:
  issues:
    types: [opened, reopened]

jobs:
  DUA-Workflow:
    runs-on: RUNNER-WHQL
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run pre-check
        id: precheck
        run: |
          ./scripts/precheck.ps1 `
            "${{ gitea.repository }}" `
            "${{ gitea.event.issue.number }}" `
            "${{ secrets.BOTTOKEN }}"

      - name: Package driver via AutoHLK (DUA)
        id: package_driver
        run: |
          ./AutoDUA.ps1 -hlkxDir "${{ steps.precheck.outputs.hlkx_folder }}"

      - name: Upload HLKX file
        id: upload_hlkx
        run: |
          ./scripts/postcomment.ps1 `
            "${{ gitea.repository }}" `
            "${{ gitea.event.issue.number }}" `
            "${{ secrets.BOTTOKEN }}"
