name: DUA Prepare
on:
  issues:
    types: [opened, reopened, edited]

jobs:
  prepare:
    runs-on: [RUNNER-WHQL]
    env:
      GITHUB_TOKEN: ${{ secrets.BOTTOKEN }}
      PARTNER_CENTER_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
      PARTNER_CENTER_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
      PARTNER_CENTER_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse Issue & Configuration
        shell: pwsh
        run: |
          ./scripts/steps/1_ParseConfig.ps1 -IssueNumber ${{ github.event.issue.number }} -RepoOwner ${{ github.repository_owner }} -RepoName ${{ github.event.repository.name }}

      - name: Download Assets
        shell: pwsh
        run: ./scripts/steps/2_DownloadAssets.ps1

      - name: Process Driver (Git Flow)
        shell: pwsh
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          SUBMITTER: ${{ github.event.issue.user.login }}
          GITHUB_TOKEN: ${{ secrets.BOTTOKEN }}
        run: ./scripts/steps/3_ProcessDriver.ps1
