name: DUA Process
on:
  issues:
    types: [opened, edited]

jobs:
  process-dua:
    if: contains(github.event.issue.labels.*.name, 'DUA')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run DUA Processing
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          # Dashboard credentials would be needed here
          # MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
        run: |
          cd dua
          python3 -m src.main
