name: Create Shipping Label
on:
  issues:
    types: [opened]

jobs:
  create-label:
    if: startsWith(github.event.issue.title, '[Shipping Label Request]:')
    runs-on: [RUNNER-WHQL]
    env:
      GITHUB_TOKEN: ${{ secrets.BOTTOKEN }}
      PARTNER_CENTER_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
      PARTNER_CENTER_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
      PARTNER_CENTER_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse Request
        shell: pwsh
        run: |
          ./scripts/steps/1_ParseRequest.ps1 -IssueNumber ${{ github.event.issue.number }} -RepoOwner ${{ github.repository_owner }} -RepoName ${{ github.event.repository.name }}

      - name: Create Label
        shell: pwsh
        run: |
          ./scripts/steps/2_CreateShippingLabel.ps1 -IssueNumber ${{ github.event.issue.number }} -RepoOwner ${{ github.repository_owner }} -RepoName ${{ github.event.repository.name }}
