name: Driver Sign Workflow

on:
  issues:
    types: [opened, reopened]

env:
  ISSUE_ID: ${{ gitea.event.issue.number }}
  GITEA_REPO: ${{ gitea.repository }}
  WORK_DIR: ./unzipped
  OUTPUT_DIR: ./output

jobs:
  driver-sign:
    runs-on: [RUNNER-HLK-26]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check attachment format
        run: |
          pwsh ./scripts/steps/pre-check.ps1

      - name: Download and extract attachment
        run: |
          pwsh ./scripts/steps/download-and-extract.ps1

      - name: Signature
        if: ${{ env.SIGN_TYPE == 'Lenovo Driver' || env.SIGN_TYPE == 'Sign file' }}
        run: |
          pwsh ./scripts/steps/sign-files.ps1

      - name: Generate CAT file
        if: ${{ env.SIGN_TYPE == 'Lenovo Driver' || env.SIGN_TYPE == 'Other Driver' }}
        run: |
          pwsh ./scripts/steps/inf2cat.ps1

      - name: Generate CAB package
        if: ${{ env.NEED_CAB == 'Yes' && env.SIGN_TYPE != 'Sign file' }}
        run: |
          pwsh ./scripts/steps/make-cab.ps1

      - name: Archive output
        run: |
          pwsh ./scripts/steps/archive-output.ps1

      - name: Issue update
        run: |
          pwsh ./scripts/steps/update-issue.ps1

      - name: Notify User
        env:
          SIGN_TEAMS_WEBHOOK_URL: ${{ secrets.SIGN_TEAMS_WEBHOOK_URL }}
        run: |
          pwsh ./scripts/steps/notify-user.ps1
