name: Process WHQL/Sign Request

on:
  issues:
    types: [opened, reopened]

jobs:
  process-request:
    # Only process issues with WHQL label (added automatically by template)
    if: contains(join(gitea.event.issue.labels.*.name, ','), 'WHQL')
    runs-on: RUNNER-WHQL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Job
        id: prepare
        shell: pwsh
        run: |
          ./scripts/PrepareHlkJob.ps1 `
            -Repository '${{ gitea.repository }}' `
            -IssueNumber '${{ gitea.event.issue.number }}' `
            -AccessToken '${{ secrets.BOTTOKEN }}' `
            -HlkxRootPath '.\HLKX'

      - name: Run Job
        id: run
        shell: pwsh
        run: |
          ./scripts/RunHlkJob.ps1 `
            -Mode '${{ steps.prepare.outputs.mode }}' `
            -TemplateFolder '${{ steps.prepare.outputs.hlkx_template_folder }}' `
            -InputHlkxFile '${{ steps.prepare.outputs.input_hlkx_file }}' `
            -DriverFolder '${{ steps.prepare.outputs.driver_folder }}' `
            -DriverProject '${{ steps.prepare.outputs.driver_project }}' `
            -Architecture '${{ steps.prepare.outputs.architecture }}' `
            -DriverVersion '${{ steps.prepare.outputs.driver_version }}'

      - name: Publish Result
        shell: pwsh
        run: |
          ./scripts/PublishHlkResult.ps1 `
            -Repository '${{ gitea.repository }}' `
            -IssueNumber '${{ gitea.event.issue.number }}' `
            -AccessToken '${{ secrets.BOTTOKEN }}' `
            -FilePath '${{ steps.run.outputs.built_hlkx_path }}'
