name: Process WHQL/Sign Request

on:
  issues:
    types: [opened, reopened]

jobs:
  process-request:
    # Only process issues that match the template title pattern "[Request]: ..."
    if: startsWith(gitea.event.issue.title, '[Request]:')
    runs-on: RUNNER-WHQL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Job
        id: prepare
        shell: pwsh
        env:
          REPO: ${{ gitea.repository }}
          ISSUE_NUM: ${{ gitea.event.issue.number }}
          TOKEN: ${{ secrets.BOTTOKEN }}
        run: |
          ./scripts/PrepareHlkJob.ps1 `
            -Repository $env:REPO `
            -IssueNumber $env:ISSUE_NUM `
            -AccessToken $env:TOKEN `
            -HlkxRootPath '.\HLKX'

      - name: Run Job
        id: run
        shell: pwsh
        env:
          MODE: ${{ steps.prepare.outputs.mode }}
          TMPL_FOLDER: ${{ steps.prepare.outputs.hlkx_template_folder }}
          INPUT_FILE: ${{ steps.prepare.outputs.input_hlkx_file }}
          DRV_FOLDER: ${{ steps.prepare.outputs.driver_folder }}
          DRV_PROJ: ${{ steps.prepare.outputs.driver_project }}
          ARCH: ${{ steps.prepare.outputs.architecture }}
          VER: ${{ steps.prepare.outputs.driver_version }}
        run: |
          ./scripts/RunHlkJob.ps1 `
            -Mode $env:MODE `
            -TemplateFolder $env:TMPL_FOLDER `
            -InputHlkxFile $env:INPUT_FILE `
            -DriverFolder $env:DRV_FOLDER `
            -DriverProject $env:DRV_PROJ `
            -Architecture $env:ARCH `
            -DriverVersion $env:VER

      - name: Publish Result
        shell: pwsh
        run: |
          ./scripts/PublishHlkResult.ps1 `
            -Repository '${{ gitea.repository }}' `
            -IssueNumber '${{ gitea.event.issue.number }}' `
            -AccessToken '${{ secrets.BOTTOKEN }}' `
            -FilePath '${{ steps.run.outputs.built_hlkx_path }}'
